DROP TABLE CASTINGS;
DROP TABLE MOVIES;
DROP TABLE STARS;


CREATE TABLE MOVIES(
  id SERIAL4 PRIMARY KEY,
  title VARCHAR(255),
  genre VARCHAR(255),
  rating INT4
);
CREATE TABLE STARS(
  id SERIAL4 PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255)
);
CREATE TABLE CASTINGS(
  id SERIAL4 PRIMARY KEY,
  movie_id INT4 ON DELETE CASCADE,
  star_id INT4 ON DELETE CASCADE,
  fee INT4,
);
