DROP TABLE CASTINGS;
DROP TABLE STARS;
DROP TABLE MOVIES;



CREATE TABLE MOVIES(
  id SERIAL4 PRIMARY KEY,
  title VARCHAR(255),
  genre VARCHAR(255),
  rating INT4
);
CREATE TABLE STARS(
  id SERIAL4 PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255)
);
CREATE TABLE CASTINGS(
  id SERIAL4 PRIMARY KEY,
  movies_id INT4 REFERENCES movies(id) ON DELETE CASCADE,
  stars_id INT4 REFERENCES stars(id) ON DELETE CASCADE,
  fee INT4
);
